### PR TITLE
Parallel kanji fix

### PR DESCRIPTION
**Pull request by konqi**
Allow multiple parallel separate kanji drawings by making helpers object methods.

### CODE REVIEW

**Comment by mbilbille** [comment]
Refuse this PR for several reason, see comments in commit.
Issue created to track this point: https://github.com/mbilbille/dmak/issues/18

**Comment by konqi** [comment]
Thank you for your feedback. Please let me elaborate on my changes.

1. **Changes to extend**: This function and the way you call it is broken, for these reasons: 
    1. Since you pass the reference to the class variable Dmak.options the class variable is changed which means that if one creates multiple Dmak objects they concurrently write to the static variable of the Dmak class
    2. In the inner loop the extend function checks for the type in the result object (instead of the source object), therefor only attributes that exist in the default options can be replaced. While this may suffice in most cases it's a nuisance to debug because it does not behave as one would expect an extend function to behave
    3. I changed the call in the constructor so each Dmak options has its own isolated options property. Without it, when I tried to create two separate kanjis the options.element was always overwritten and the result was that the output would always be rendered in a single element, instead of two.
2. **Migration of helpers into Dmak class**: I wanted to fix that Dmak uses the static Dmac.options property because those are shared between all Dmak instances. Passing options to the helpers and use the parameter instead of Dmak.options was my first attempt. But then I thought about it and realized that if the rendering is done with options from the object it becomes object behavior and not class behavior. Therefor it made sense to change them from functions to class methods. I realize that I should've removed all now redundant parameters, like stroke, etc.. 

Anyway, It took me a couple of hours to diagnose that I didn't do anything wrong in the handleing of Dmak, it just can't handle multiple drawings. Since I just wanted to see how two separate drawings would look like I only fixed it this far, to make it work at least.

I was under the impression that the ability to draw multiple kanjis in parallel by using proper isolation would be a major improvement. I'm happy if you consider fixing this yourself. Usually though if a library on github doesn't change for two years it means that it won't change again any time soon.

I decided to not use the library at all even before I created the code for the pull request (not your fault, it just doesn't fit with the rest of the page), so I'm a bit sad that it turns out to be a major waste of my time.

**Comment by mbilbille** [comment]
Thanks again @konqi for your work. First at all this is not a waste of time, the issue you raised up is 100% valid and a dedicated issue has been created to track it. Your code is neither a waste, I will be a useful base of code to fix this issue. I did not accept the PR because I didn't want to commit it as it is. I hope you understand that.

**Changes to extend** : as I said, I didn't attempt to offer to proper `extend` function. Like `jQuery`, `Underscore` or `Lodash`. But only keep it simple as possible to overload a set of options. 

> therefor only attributes that exist in the default options can be replaced

Yes that exactly that is exactly what the function is attempt to do. Named the function `extend` was a mistake `assign` would had been better.

I agree on (i) and (iii) and will be covered by #18 

**Migration of helpers into Dmak class** : Usage of Dmak.options everywhere in code is core issue here and by design Helper function should NOT reference object instance within its implemenation but rather take an instance as parameter and produce a result. I would like to keep Dmak.fn, which are functions exposed on Dmak object minimalistic, `prepare`, `erase`, `render`, `pause`, `eraseLastStrokes` and `renderNextStrokes` are pretty straightforward. No point to expose internal function. Having say that, the current implementation is broken, we agreed on that :) 

> Anyway, It took me a couple of hours to diagnose that I didn't do anything wrong in the handleing of Dmak, it just can't handle multiple drawings. Since I just wanted to see how two separate drawings would look like I only fixed it this far, to make it work at least.   

100% OK with you on this and thank you for your time and effort. 

> I was under the impression that the ability to draw multiple kanjis in parallel by using proper isolation would be a major improvement. I'm happy if you consider fixing this yourself. Usually though if a library on github doesn't change for two years it means that it won't change again any time soon.

Definitively, it will be a valuable asset to improve Dmak. Point is not who fix it or I should say under which name code is committed. The library has not changed on past year because I did not receive any request to. But I always try to be reactive when someone ask something or push a PR.

> I decided to not use the library at all even before I created the code for the pull request (not your fault, it just doesn't fit with the rest of the page), so I'm a bit sad that it turns out to be a major waste of my time.

I am sad too, but always open to suggestions and feedbacks.

**Comment by mbilbille** [comment]
@konqi issue #18 has been fixed.
Hope you're happy with that.

**Pull request closed without merging**
